### ISSUE TITLE
MacOS version not updated in 0.4.0 release

### ISSUE THREAD

**Issue by rquadling** [cycloidio/terracognita#103]
**General information:**

* Operating System: MacOS Catalina 10.15.4
* Terracognita version / tag: The current version is: v0.3.0-65-g72cf96b
* Did you build Terracognita from sources or did you use the Docker image: Downloaded from [here](https://github.com/cycloidio/terracognita/releases/download/v0.4.0/terracognita-darwin-amd64.tar.gz).

**Describe the bug:**

Running:
```
$ curl -L https://github.com/cycloidio/terracognita/releases/download/v0.4.0/terracognita-darwin-amd64.tar.gz -o terracognita-darwin-amd64.tar.gz && tar -xf terracognita-darwin-amd64.tar.gz && chmod +x terracognita-darwin-amd64 && ./terracognita-darwin-amd64 version
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   645  100   645    0     0   1514      0 --:--:-- --:--:-- --:--:--  1514
100  101M  100  101M    0     0   9.9M      0  0:00:10  0:00:10 --:--:-- 11.1M
The current version is: v0.3.0-65-g72cf96b
```

**Comment by tormath1** [comment]
Hi @rquadling , 

Thanks for raising this! It's a known issue with our CI configuration: the version displayed is `v0.3.0-65` but the commit https://github.com/cycloidio/terracognita/commit/72cf96b1c1394223105246d9269042581f9f3267 is associated to the `v0.4.0` release. 

```shell
$ git show-ref --tags | grep 0.4.0
72cf96b1c1394223105246d9269042581f9f3267 refs/tags/v0.4.0
```

The binary you downloaded is built with the good commit but the version displayed is not the good one, this glitch should disappear in the next release. I let the issue open until then.

**Comment by rquadling** [comment]
OK. Thank you.

**Comment by rquadling** [comment]
How soon for a new release?

**Comment by tormath1** [comment]
Hi @rquadling, 

We just released the version `0.5.0` of Terracognita: https://github.com/cycloidio/terracognita/releases/tag/v0.5.0. The version error should be solved, let us know !

**Comment by rquadling** [comment]
Unfortunately, the version number is not correct.

```
$ which terracognita 
/usr/local/bin/terracognita

$ md5sum /usr/local/bin/terracognita
b0f3fcdd4571b7670264a85c65f65b7d  /usr/local/bin/terracognita

$ terracognita version
The current version is: v0.4.0-58-g1a62e7d
```

**Comment by tormath1** [comment]
Hi @rquadling , 

this is strange. Did you pull the [latest](https://github.com/cycloidio/terracognita/releases/tag/v0.5.0) release ? Your MD5 checksum does not fit with what I have:

```
$ curl -L https://github.com/cycloidio/terracognita/releases/download/v0.5.0/terracognita-darwin-amd64.tar.gz -o terracognita-darwin-amd64.tar.gz
$ tar -xf terracognita-darwin-amd64.tar.gz
$ md5sum terracognita-darwin-amd64
d8120928e120582dcd2e54a48ce212b4  terracognita-darwin-amd64
```

I tested with a MacOS and version `0.5.0` was displayed.

**Comment by rquadling** [comment]
I just repeated the exercise and got the right version and hash.

It must have been a LONG day.
