### ISSUE TITLE
False error (and so retry loop).

### ISSUE THREAD

**Issue by rquadling** [cycloidio/terracognita#106]
**General information:**

* Operating System: MacOS Catalina 10.15.4
* Terracognita version / tag: 0.4.0 (though shows as 0.3.0-g...yeah, reported that already).
* Did you build Terracognita from sources or did you use the Docker image:  from releases.

**Describe the bug:**

When there is no AWS password policy, this is usual 3 retries to find that there is no policy.

**Comment by xescugc** [comment]
With #109 this delay would be handled :)
