### ISSUE TITLE
Unable to import more than 100 IAM roles

### ISSUE THREAD

**Issue by yashkatta25** [cycloidio/terracognita#129]
**General information:**

* Operating System: centos 7
* Terracognita version / tag: v0.3.0
* Did you build Terracognita from sources or did you use the Docker image: Sources

**Describe the bug:**
When trying to import IAM roles and IAM users it only imports configurations for first 100 resources.

**Agenda**: We want to import 200+ IAM roles 

**Log message**
It imports till first 100 iam roles
![image](https://user-images.githubusercontent.com/34921050/87767604-839c3e00-c838-11ea-9b19-a9994327cddf.png)

Whereas resource count is more than 100
![image](https://user-images.githubusercontent.com/34921050/87767732-b5ada000-c838-11ea-92b3-e52d5f70d551.png)

**Comment by xescugc** [comment]
Yes, this was an issue with "old" versions, with `0.5.0` we have Pagination on AWS Resources, so if you could update to 0.5 and check again :)

**Comment by yashkatta25** [comment]
@xescugc thanks its working
