### ISSUE TITLE
homebrew support

### ISSUE THREAD

**Issue by chenrui333** [cycloidio/terracognita#153]
FYI, I have just added some [homebrew support](https://github.com/Homebrew/homebrew-core/pull/66627) for this utility.

**Comment by xescugc** [comment]
Hi!

First of all thanks for that!

I was wondering if it would be possible to have a recipe that it's not just tag to one specific version. If we release new versions we'll have to manually update that one too. And for the specific versions you could `wget` the binary from git as it would be easier too.

Also if it possible to add it to the README too and if they have a badge also :)

**Comment by chenrui333** [comment]
yeah, I will do after the PR got merged.

**Comment by chenrui333** [comment]
It got shipped, so I filed a homebrew installation support PR. 🎉
