### ISSUE TITLE
Problems with Terracognita on Azure

### ISSUE THREAD

**Issue by manfred0191** [cycloidio/terracognita#190]
**General information:**

* Operating System:  Windows 10 Ubuntu Linux
* Terracognita version / tag: 1.0.1
* Did you build Terracognita from sources or did you use the Docker image: docker

**Describe the bug:**

When I use terraform plan I get the error message

│ Error: Unsupported argument
│
│   on resources.tf line 77, in resource "azurerm_virtual_network" "vuPyn":
│   77:   tc_category = "network_resources"
│
│ An argument named "tc_category" is not expected here.
╵

**Log message**

Here you can paste the log message or paste the link to console logs. If the log message is too big, you can use a tool like https://pastebin.com/.

**Additional context**

**Comment by xescugc** [comment]
Hi @manfred0191 .

I think this issue is already fixed with https://github.com/cycloidio/terracognita/pull/187 which is not part of a release yet. I'll prepare a release so this can be pulled using an specific tag.

**Comment by xescugc** [comment]
Ok with the latest version `0.7.0` this will be solved as it included the change that was on master/latest.

**Comment by manfred0191** [comment]
Can I for now remove that line from the tf-file?
