### ISSUE TITLE
Cannot connect to Google Cloud

### ISSUE THREAD

**Issue by manfred0191** [cycloidio/terracognita#196]
Today I wanted to use Terracognita with Google Cloud but I was unable to connect to the Google cloud and got this error message:

mkoeller01@SKYSCRAPER1:/mnt/c/Users/Manfred/Downloads/linux/created_environments/google_webserver_terracognita$ terracognita google --hcl app/outputs/resources.tf --region us-central1 --project starlit-cocoa-318709 --credentials /mnt/c/Users/Manfred/Downloads/starlit-cocoa-318709-6c9fd9234997.json
Error: could not initialize 'terraform/google.Config.LoadAndValidate()' because: unable to parse credentials from '/mnt/c/Users/Manfred/Downloads/starlit-cocoa-318709-6c9fd9234997.json': invalid character '/' looking for beginning of value
could not initialize 'terraform/google.Config.LoadAndValidate()' because: unable to parse credentials from '/mnt/c/Users/Manfred/Downloads/starlit-cocoa-318709-6c9fd9234997.json': invalid character '/' looking for beginning of value

**Comment by sdurrheimer** [comment]
Hello @manfred0191,

Can you make sure your JSON credentials file is valid and readable, the error appears to be within that file.

**Comment by manfred0191** [comment]
It definitely is, because Terraformer can handle it, the same file. Therefore the file cannot be the reason

**Comment by manfred0191** [comment]
I attach the anonymized file I am using. Maybe you find the erro
[mycredentials.json.txt](https://github.com/cycloidio/terracognita/files/6775877/mycredentials.json.txt)
r when you take a look at it. Is it the \ in the Key that is the reason?

**Comment by sdurrheimer** [comment]
Not sure about the `s` (might be part of the key) but the `-----BEGIN PRIVATE KEY-----\s` seems weird, I would say it should be either:
- `-----BEGIN PRIVATE KEY-----\ns`
or
- `-----BEGIN PRIVATE KEY-----\n`

as there should be a `\n` between the private key header and the actual key.

**Comment by manfred0191** [comment]
I created another json-File in the Google Cloud. Unfortunately it is the same error, although the section created by Google now begins with -----BEGIN PRIVATE KEY-----\n

Somehow terracognita seems to have a problem with the sign /

**Comment by sdurrheimer** [comment]
> Somehow terracognita seems to have a problem with the sign /

Not really, I did some tests with my own credentials with a bunch of `/` in it and I don't have any issue.
We are using the [Terraform Google Provider](https://github.com/cycloidio/terracognita/blob/master/google/provider.go#L12) library to handle the credentials, so there is no reason for that part to not understand a valid google credential.

What terracognita version are you using? Did you download it from our releases or did you build it yourself?

**Comment by manfred0191** [comment]
Sorry I didn't fill that out.

I am running Terracognita from the Docker image on a WSL linux system

**Comment by manfred0191** [comment]
But just to repeat that: Terraformer, which is a competitor, runs perfectly with the same file! So the file itself cannot be the reason for the error occuring

**Comment by sdurrheimer** [comment]
> Sorry I didn't fill that out.
> 
> I am running Terracognita from the Docker image on a WSL linux system

Could you be more precise about the version of terracognita / tag of that docker image, as well as the command used to run the docker image?

> But just to repeat that: Terraformer, which is a competitor, runs perfectly with the same file! So the file itself cannot be the reason for the error occuring

In my last response, I moved away from the idea of you having a problem with-in the credentials (even tho the missing `n` was a real one).
My current assumption is that the credential file is not accepted because it is given as an absolute path instead of a relative one.
It was a real issue on the Google Terraform provider side at some point, which is why I wanted to know the terracognita version you are using.

To illustrate this, there is a good chance that it would work it you changed the following:
```bash
--credentials /mnt/c/Users/Manfred/Downloads/starlit-cocoa-318709-6c9fd9234997.json
```
by:
```bash
--credentials ../../../starlit-cocoa-318709-6c9fd9234997.json
```
or if moving the credential file to the same directory were you are executing Terracognita:
```bash
--credentials starlit-cocoa-318709-6c9fd9234997.json
```

**Comment by manfred0191** [comment]
Hi Steve, thanks that you are so patient with me ;)

Unfortunately, this doesn't work either, but the error message is different although it's the same credentials file that is being used,

The different commands and their outputs:

mkoeller01@SKYSCRAPER1:/mnt/c/Users/Manfred/Downloads/linux/created_environments/google_webserver_terracognita$ terracog
nita google --hcl app/outputs/resources.tf --region us-central1 --project starlit-cocoa-318709 --credentials /mnt/c/User
s/Manfred/Downloads/starlit-cocoa-318709-6c9fd9234997.json
Error: could not initialize 'terraform/google.Config.LoadAndValidate()' because: unable to parse credentials from '/mnt/c/Users/Manfred/Downloads/starlit-cocoa-318709-6c9fd9234997.json': invalid character '/' looking for beginning of value
could not initialize 'terraform/google.Config.LoadAndValidate()' because: unable to parse credentials from '/mnt/c/Users/Manfred/Downloads/starlit-cocoa-318709-6c9fd9234997.json': invalid character '/' looking for beginning of value
Usage:
  terracognita google [flags]
  terracognita google [command]


mkoeller01@SKYSCRAPER1:/mnt/c/Users/Manfred/Downloads/linux/created_environments/google_webserver_terracognita$ terracognita google --hcl app/outputs/resources.tf --region us-central1 --project starlit-cocoa-318709 --credentials ../../../starlit-cocoa-318709-6c9fd9234997.json
Error: could not initialize 'terraform/google.Config.LoadAndValidate()' because: unable to parse credentials from '../../../starlit-cocoa-318709-6c9fd9234997.json': invalid character '.' looking for beginning of value
could not initialize 'terraform/google.Config.LoadAndValidate()' because: unable to parse credentials from '../../../starlit-cocoa-318709-6c9fd9234997.json': invalid character '.' looking for beginning of value
Usage:
  terracognita google [flags]
  terracognita google [command]



mkoeller01@SKYSCRAPER1:/mnt/c/Users/Manfred/Downloads/linux/created_environments/google_webserver_terracognita$ terracognita google --hcl app/outputs/resources.tf --region us-central1 --project starlit-cocoa-318709 --credentials starlit-cocoa-318709-6c9fd9234997.json
Error: could not initialize 'terraform/google.Config.LoadAndValidate()' because: unable to parse credentials from 'starlit-cocoa-318709-6c9fd9234997.json': invalid character 's' looking for beginning of value
Usage:
  terracognita google [flags]
  terracognita google [command]



3 different error messages.


I am using terracognita with this command:


alias terracognita='docker run -v /home/mkoeller01/outputs:/app/outputs cycloid/terracognita'

The current version is : v0.6.4

**Comment by sdurrheimer** [comment]
> I am using terracognita with this command:
> 
> alias terracognita='docker run -v /home/mkoeller01/outputs:/app/outputs cycloid/terracognita'
> 
> The current version is : v0.6.4

OK this helps me a lot.

So what is happening is that terracognita can't access your credential because the path where it is located is not shared with the terracognita container via a volume.

the following should solve your problem:
```bash
alias terracognita='docker run -v /home/mkoeller01/outputs:/app/outputs -v /mnt/c/Users/Manfred/Downloads:/mnt/c/Users/Manfred/Downloads cycloid/terracognita'
```
with that your `terracognita google --hcl app/outputs/resources.tf --region us-central1 --project starlit-cocoa-318709 --credentials /mnt/c/Users/Manfred/Downloads/starlit-cocoa-318709-6c9fd9234997.json` command should work.

**Comment by manfred0191** [comment]
Yes, that was the reason! Thank you so much

Now I am coming until this is occuring:

Starting Terracognita with version v0.6.4
Importing with filters:
        Tags:    [],
        Include: [],
        Exclude: [],
        Targets: [],
Importing google_compute_instance [2/2] Done!
Importing google_compute_firewall [5/5] Done!
Importing google_compute_network [1/1] Done!
Importing google_compute_health_check [1/1] Done!
Importing google_compute_instance_group [1/1] Done!
Importing google_compute_instance_iam_policy [1/2]Error: could not import from google: error while calculating the Config of resource "google_compute_instance_iam_policy": provider google with resource google_compute_instance_iam_policy is not supported

**Comment by manfred0191** [comment]
I am opening a separate issue for this

**Comment by manfred0191** [comment]
Problem is solved.
