### ISSUE TITLE
terracognita for redis setup

### ISSUE THREAD

**Issue by Manoj-07** [cycloidio/terracognita#206]
If I am trying to convert my redis-setup shell script files to redis -setup hcl files by using terracognita I am not getting changed, could you please let me know how to change it.(I had already used flag include also)
![Screenshot from 2021-07-22 18-04-15](https://user-images.githubusercontent.com/64740477/126640129-17d33ff8-7754-4f74-8003-97c93979f498.png)

**Comment by talset** [comment]
It seems you are trying to do `terracognita aws ... -i redis-setup.sh`

`-i, --include` Is the list of resources to import, these names are the ones on TF (ex: aws_instance). If not set then means that all the resources will be imported

`redis-setup.sh` is not a valid terraform resource.

terracognita is used to generate terraform files from your existing infrastructure on your Cloud Provider.
If your `redis-setup.sh` create resources like `aws_elasticache_cluster` on AWS, I suggest running
`terracognita aws ... -i aws_elasticache_cluster`

**Comment by Manoj-07** [comment]
While I am trying to run that command( terracognita .....    -module terra --include aws_elasticache_cluster) I am getting an empty terraform file that does not consist of the above changes also.While I am trying to run (--i) it is showing that it is an invalid flag.
![Screenshot from 2021-07-22 21-14-28](https://user-images.githubusercontent.com/64740477/126668593-1c0a3238-2708-4b3e-8330-79d3e1f92237.png)

**Comment by talset** [comment]
The short flag for `--include` is `-i` not `--i`

`aws_elasticache_cluster` was a suggestion. Since you mentioned `redis-setup.sh` script, I supposed you were using Elasticache Cluster but I might be wrong.

What do you have in `redis-setup.sh` ?

**Comment by Manoj-07** [comment]
I am having my aws elastic cache redis deployment.

**Comment by talset** [comment]
`terracognita` is used to generate terraform files from an existing infrastructure on your cloud provider.
terraform resources supported by `terracognita` can be found with `terracognita aws resources`.

`terracognita` only generates terraform files from cloud provider API and does not read or write a shell script.
We might not be able to help you with shell script conversion.

**Comment by Manoj-07** [comment]
okay, sir. Thank you for your information.
