### ISSUE TITLE
System freezes and fails to compile.

### ISSUE THREAD

**Issue by rohitghali** [cycloidio/terracognita#217]
**General information:**

* Operating System: ArchLinux
* Terracognita version / tag: terracognita-git aur package
* Did you build Terracognita from sources or did you use the Docker image:  Built from source

**Describe the bug:**

Tried building via make install and AUR git version. Both has the same problem. System freezes while compiling and after a while fails. I'm pasting the log below. Please do check and provide a solution asap. Thanks in advance.

**Log message**

Cloning into 'terracognita-git'...
done.
==> Starting pkgver()...
==> Updated version: terracognita-git 1:v0.7.1.r16.ge068a21-1
==> Sources are ready.
==> Making package: terracognita-git 1:v0.7.1.r16.ge068a21-1 (Thu 12 Aug 2021 05:06:40 PM IST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Starting build()...
go build github.com/Azure/azure-sdk-for-go/services/datafactory/mgmt/2018-06-01/datafactory: /usr/lib/go/pkg/tool/linux_amd64/compile: signal: killed
==> ERROR: A failure occurred in build().
    Aborting...
error making: terracognita-git

**Additional context**

**Comment by rohitghali** [comment]
Solved. For the people looking her for solution, it's an OOM error. add swap storage and it's solved. Closing this.

**Comment by xescugc** [comment]
Building locally Terracognita consumes a lot of memory due do big dependencies, we want to try to find a solution but it's not "easy" hehe.
