### ISSUE TITLE
AWS provider giving some gibberish in tags.

### ISSUE THREAD

**Issue by rohitghali** [cycloidio/terracognita#218]
**General information:**

* Operating System: ArchLinux
* Terracognita version / tag: git build
* Did you build Terracognita from sources or did you use the Docker image: Built from sources.

**Describe the bug:**

Getting gibberish and many errors. Doesn't happen with others like terraformer

**Log message**

Missing attribute separator: Expected a newline or comma to mark the beginning of the next attribute. HCL

**Additional context**

![image](https://user-images.githubusercontent.com/42379398/129223455-34067ca0-c551-43fe-9721-a613d648ae33.png)

**Comment by xescugc** [comment]
Could I get more context on this error?

A bit more of the surrounding HCL and which is the expected result? Just to know which part are we parsing incorrectly.

**Comment by rohitghali** [comment]
> Could I get more context on this error?
> 
> A bit more of the surrounding HCL and which is the expected result? Just to know which part are we parsing incorrectly.

That colon is probably the mistake. When I apply the same config again, it throws a syntax error.

**Comment by xescugc** [comment]
Ok I think I know what it may be causing this, I'll check. I think is related that we try to make a reference between the value of `"lambda:creaedBy"` from this resource to another, but tags cannot do that as the keys (such in this case) are user input, the HCL formatter is the one splitting the `lambda : craetedBy` but we are the one trying to create the interpolation.

**Comment by xescugc** [comment]
Which command did you use? Flags and so on just to be sure :).

**Comment by rohitghali** [comment]
I don't remember unfortunately. Is it absolutely essential? I'll try to find out if absolutely necessary.

**Comment by xescugc** [comment]
It was just to be sure of what I was fixing, but I'm quite sure the PR will solve it
