### ISSUE TITLE
Minimal documentation about how to add support for a cloud provider

### ISSUE THREAD

**Issue by remyleone** [cycloidio/terracognita#248]
### Abstract

Could you add documentation explaining how a given cloud vendor/terraform provider implementer can add support for their provider inside terracognita?
What are the difficult aspects? How is it tested? Documented?

On the code generation perspective, could you give a brief overview about how terracognita works from a software architecture perspective?

I'm available for review as an external contributor :)

**Comment by xescugc** [comment]
I'll add this documentation on https://github.com/cycloidio/terracognita/blob/master/CONTRIBUTING.md, I'll also recheck if that's 100% up to date or there is something missing or changed.

**Comment by xescugc** [comment]
You can find the documentation on https://github.com/cycloidio/terracognita/blob/master/CONTRIBUTING.md#add-a-new-provider
