### ISSUE TITLE
aws doesn't initialize for govcloud credentials

### ISSUE THREAD

**Issue by rirze** [cycloidio/terracognita#253]
**General information:**

* Operating System: Ubuntu 20.04
* Terracognita version / tag: v0.7.4
* Did you build Terracognita from sources or did you use the Docker image: source

**Describe the bug:**
 Using Govcloud credentials fails with the following error 
```
could not initialize 'reader' because: InvalidClientTokenId: The security token included in the request is invalid.
	status code: 403, request id: 77795d87-8696-4ad7-898c-d0ecdafc4a6b
```
I have used all combinations of command flags and environment variables to test if something would work, but it does not. To make sure my credentials were valid, I ran serveral `aws ...` commands, and they ran succesfully. 

As a control, I am able to connect to another account in `us-east-1` and `terracognita` works for me there. 

**Log message**

```
could not initialize 'reader' because: InvalidClientTokenId: The security token included in the request is invalid.
	status code: 403, request id: 77795d87-8696-4ad7-898c-d0ecdafc4a6b
```

**Additional context**

I tried looking through the code for anything that would break for Govcloud or regions like `us-gov-west-1` but I couldn't find anything. I suspect it's something special about the region that breaks the initializer.

**Comment by jkarmstr-seed** [comment]
https://github.com/cycloidio/terracognita/blob/270ebba2996439a4b8c51f4343b631f0708a56f5/aws/reader/connector.go#L170
Some accounts are region dependent (e.g. GovCloud). Validating against Europe won't work.

**Comment by rirze** [comment]
@jkarmstr-seed Between the months-long lack of reply, I'm going to assume the cycloidio team don't particularly care about this issue. 

I have since worked at different company and gone back to using terraformer for extracting Terraform resources out of Govcloud environments. I suggest anyone else to do the same.

**Comment by xescugc** [comment]
Sorry for this huge delay, for some reason my notifications got mixed/lost for this issues.

I've opened a PR with the change suggested by @jkarmstr-seed as it makes sense, we had that `defaultRegion` as a leftover on another library we had that we exported the code to TerraCognita.

The PR is https://github.com/cycloidio/terracognita/pull/265, for now I'll not close this issue as we do not own a GovCloud account and cannot test it, once the PR is merged you could test if that solved the issue :smile:

**Comment by jkarmstr-seed** [comment]
Solved the authentication on the fg-253 branch
________________________________

**Comment by xescugc** [comment]
Perfect! then I'll close the issue and we'll release shortly :)

Thanks you @jkarmstr-seed :)
