### ISSUE TITLE
Azure: Link between dependency resources must be ensured

### ISSUE THREAD

**Issue by xlr-8** [cycloidio/terracognita#278]
### Abstract

The link between dependency resources must be ensured. For example, when creating a vm, the network_interface_ids or the public_ip_id in the config_ip blockattribute must point to the terraform resource created alongside with the main resource using interpolation.

**Comment by xescugc** [comment]
AFAIK this is working on all providers as the logic is not provider dependent, we have to be able to reproduce it before fixing anything.

**Comment by xescugc** [comment]
We figure it out that the AZ IDs are case insensitive, so some have capital letters and some do not even if it's the same ID. We'll apply lowcase to all the AZ IDs when linking.

**Comment by xescugc** [comment]
This has been partially done in https://github.com/cycloidio/terracognita/pull/338 for the `availability_set_id`
