### ISSUE TITLE
Azure: support for availability sets

### ISSUE THREAD

**Issue by xlr-8** [cycloidio/terracognita#280]
### Abstract

Terracognita must assign availability set id in the azurerm_virtual_machine whenever possible.

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/availability_set
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine#availability_set_id

**Comment by marcoldp** [comment]
I tested the import with the new added resources (vm linux/windows) and it seems that the id is set. Otherwise the availabilty set resources is supported
