### ISSUE TITLE
Azure: managed disk attribute isn't set correctly

### ISSUE THREAD

**Issue by xlr-8** [cycloidio/terracognita#281]
### Abstract

When importing a managed disk with createOption = "FromImage", the attribute managed_disk_id is still set and needs to be removed. In general, when createOption is different than Attach, managed_disk_id attribute must be removed.

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine#managed_disk_id

**Comment by xescugc** [comment]
IIRC the test I did RN it does not fail anymore, but I would not target this issue until we support the new `linux/windows_virtual_machines` because that may solve it as this is from the deprecated `virtual_machines`. And also if it's not failing RN IDK if it has to be fixed.

**Comment by marcoldp** [comment]
Tested locally with the new resources and didn't found the issue. in any case the atribute doesn't seem to exist in the new resources
