### ISSUE TITLE
Override of ip configuration

### ISSUE THREAD

**Issue by nicolasThal** [cycloidio/terracognita#285]
**General information:**

* Operating System: Ubuntu 22.04
* Terracognita version / tag: v0.7.4
* Did you build Terracognita from sources or did you use the Docker image: Download from sources

**Describe the bug:**

I have exported my configuration for a cloudSql instance on GCP. I have 3 firewall rules to allow 3 different IP to directly query the database instance.

In the tfstate file, the correct configuration is set. I can see the three different IP address with their associated name.

In the module file, I have 3 entries in the `ip_configuration.authorized_networks` key.
When I look closer, I see that the generated variable name is the same for all three entries : 

```yaml
    ip_configuration {
      authorized_networks {
        name  = var.google_sql_database_instance_infra_services_uat_ssd_settings_ip_configuration_authorized_networks_name
        value = var.google_sql_database_instance_infra_services_uat_ssd_settings_ip_configuration_authorized_networks_value
      }

      authorized_networks {
        name  = var.google_sql_database_instance_infra_services_uat_ssd_settings_ip_configuration_authorized_networks_name
        value = var.google_sql_database_instance_infra_services_uat_ssd_settings_ip_configuration_authorized_networks_value
      }

      authorized_networks {
        name  = var.google_sql_database_instance_infra_services_uat_ssd_settings_ip_configuration_authorized_networks_name
        value = var.google_sql_database_instance_infra_services_uat_ssd_settings_ip_configuration_authorized_networks_value
      }
```

Should it be my responsibility to update all of those variables ?

If not, could you help me creating a fix for this issue ?

**Comment by xescugc** [comment]
Ok we also identified that already on our side and I'll work on fixing it :) I thought we already had it fixed as I recall conversations about it with other colleagues.

**Comment by nicolasThal** [comment]
Thank you @xescugc for your help.

I will test it as soon as I can !

**Comment by xescugc** [comment]
Is on `master` now :) It'll be included on the next release ( no date yet )
