### ISSUE TITLE
Provide Pre-buillt binaries for Terracognita

### ISSUE THREAD

**Issue by mechastorm** [cycloidio/terracognita#31]
It would be nice if a pre-built binary for Terracognita can be provided as part of the release. This will help newcomers to try out the tool themselves without having to resort to building it themselves with the GoLang tools. 

Numerous projects including Terraform have been able to auto-build this as part their CI/CD pipeline, so I am sure this is doable for Terracognita project as well.

**Comment by xescugc** [comment]
The next version will have them :smile:

**Comment by xescugc** [comment]
https://github.com/cycloidio/terracognita/releases here it's!

**Comment by mechastorm** [comment]
Thank You!
