### ISSUE TITLE
panic during parsing

### ISSUE THREAD

**Issue by thoellrich** [cycloidio/terracognita#36]
Using docker to pull the latest version of terracognita I attempted to import a medium sized AWS account. Ran into the ListBuckets issue mentioned in issue #29. Reran with `--exclude=aws_s3_bucket`, which seemed to run almost to completion. After showing SES related DEBUG output, I got the following `panic()`:

```
Error: could not import from AWS: error while fmt HCL: In <standard input>: At 9438:5: expected: IDENT | STRING | ASSIGN | LBRACE got: NUMBER
error while Sync Config
github.com/cycloidio/terracognita/provider.Import
        /app/provider/import.go:73
github.com/cycloidio/terracognita/cmd.glob..func1
        /app/cmd/aws.go:66
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
main.main
        /app/main.go:11
runtime.main
        /usr/local/go/src/runtime/proc.go:200
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337
```

**Comment by xescugc** [comment]
Ok this error is because something in the internal structure that we have of the current HCL it's not correct for the HCL Format and it's impossible to reproduce it from my side :cry: .

But we have plan to add `-v` https://github.com/cycloidio/terracognita/issues/17 which when enabled, one of the things we'll print is what's going to be Formatted so we'll be able to identify why this is happening to you.

Once that Issue is closed I'll comment again to ask you to use the flag to get more info and solve this issue :smile: .

**Comment by thoellrich** [comment]
Yeah, it look like it to me when I inspected `hcl.Sync()` :-(

Maybe add an option to save the intermediate JSON?

I'd be happy to provide more details when more debugging options are available.

Thanks

**Comment by xescugc** [comment]
Ok we've added on `master` the https://github.com/cycloidio/terracognita/pull/38 with the `--verbose` and `--debug` flag. The `--verbose` it's enough on this case if you want to try again :).

**Comment by thoellrich** [comment]
Hi Francesc,

thanks for letting me know about the added options. I just pulled the latest container and re-ran the same command line twice: once with `--verbose` added and a 2nd time with `--verbose` and `--debug` added. In both cases I got the same error message as before with a slightly different line number (infrastructure has changed):
```
Error: could not import from AWS: error while fmt HCL: In <standard input>: At 9491:5: expected: IDENT | STRING | ASSIGN | LBRACE got: NUMBER
error while Sync Config
github.com/cycloidio/terracognita/provider.Import
        /app/provider/import.go:114
```

Just before the error, I see the following two log lines with a long JSON string and a long HCL string:

```
ts=2019-07-18T11:58:52.304092459Z caller=hcl.go:85 func=writer.Write(HCL) msg="parsing internal config to HCL" json="{\"resource\":{...
ts=2019-07-18T11:58:52.59422038Z caller=hcl.go:97 func=writer.Write(HCL) msg="formatting HCL" hcl="\"resource\"...
```

I grabbed the contents from both lines and used some sed/tr to create `out.json` and `out.hcl`. Both files are syntactically correct and can be parsed using `python -mjson.tool` and `terraform fmt -` respectively. So just looking at what's logged, I don't see any format errors.

I assume the error happens when you parse the HCL from the 2nd log line? 

The `out.hcl` file begins like this and ends with a `aws_vpc` definition:
```
"resource" "aws_alb" "aLYvM" {
  "access_logs" = {
    "bucket" = ""
  }

  "enable_http2" = true

  "idle_timeout" = 60

  "ip_address_type" = "ipv4"
...
```

Looking at line number 9491 (from the error message above) I'm in the middle of an `aws_iam_policy`, but nothing looks suspicious. 

Obviously I can't share all the JSON/HCL with you, but I'd be happy to provide more details, if you can tell me what to look for.

**Comment by thoellrich** [comment]
I found it :-)

The bug is in `FormatHCL()` and the first regexp for `// Replace all the "key" = "value" for key = "value"`.

Our EC2 instances happen to have tags that begin with a number (don't ask why). In the HCL before you apply `FormatHCL()`, I can see the tags as:
```
  "tags" = {
    "2tag" = "2value"
    "other_tag" = "other value"
```
Your `FormatHCL()` turns it into:
```
  tags {
    2tag = "2value"
    other_tag = "other value"
```
which `fmtcmd.Run()` complains about. 

I have not tried it yet, but I think if you turn the first regexp into:
```
    regexp.MustCompile(`"([^0-9][\w\-_\.]+)"\s=`)
```
it could work.

**Comment by xescugc** [comment]
Ok I've pushed a quick fix with test for this, before opening the PR could you test branch `fg-36` to see if it solve the issue you have?

**Comment by thoellrich** [comment]
I can confirm that branch `fg-36` fixes the issue I encountered. Thanks for the quick resolution!

**Comment by xescugc** [comment]
Yes, we have branch that migrates to TF 0.12 format https://github.com/cycloidio/terracognita/pull/33 which the last commit improves this.
