### ISSUE TITLE
Be able to import by target (resources+IDs)

### ISSUE THREAD

**Issue by xescugc** [cycloidio/terracognita#40]
Make it work like `terraform import` which can only import by [target](https://www.terraform.io/docs/commands/plan.html#resource-targeting) (resource+ID) so have a parameter to be able to define an ID (or list) to import.

Could also improve it to be able to do something like `--target "aws_instance:1,2,3" --target "aws_iam_user:1,2,3"` so we could import multiple resources with multiple IDs.

**Comment by tormath1** [comment]
closed by https://github.com/cycloidio/terracognita/pull/80
