### ISSUE TITLE
Support AWS profiles/config

### ISSUE THREAD

**Issue by tyrken** [cycloidio/terracognita#48]
Don't insist on an AWS key/secret-key, ideally use profiles as the standard AWS SDK supports them.

Accepting a session-token parameter might be a vaguely acceptable mid-way step for your code...

**Comment by xescugc** [comment]
Ok I've read now about it https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html.

We tried to keep it close to Terraform and I see that it also supports them https://www.terraform.io/docs/providers/aws/index.html#environment-variables so we'll add it :).

**Comment by kevit** [comment]
any luck here? which kind of help you need?

**Comment by xescugc** [comment]
Ok so for this issue what we need is:

* 2 new flags/ENV: `SHARED_CREDENTIALS_FILE` and `PROFILE` which should works as defined in https://www.terraform.io/docs/providers/aws/index.html#shared-credentials-file. Basically reading the file with the specific profile and set the required keys to the config to proceed.

Also would be good to make aliases for all the `AWS` envs to also support them with `AWS_PROFILE`, `AWS_SHARED_CREDENTIALS_FILE`, `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` and `AWS_DEFAULT_REGION` as those are the more standar ones used by everyone.

@kevit if you want you are welcome to work on it :) just say it so I rely on you doing it :smile: . If not I'll take it :smile:

**Comment by kevit** [comment]
Actually @xescugc there is not so much to change, https://github.com/cycloidio/terracognita/compare/master...kevit:master 
I should just prepare a right if and PR

**Comment by xescugc** [comment]
Just as an small note:

* You are replacing the previous behavior to JUST support `SHARED_CREDENTIALS_FILE` and `PROFILE`. Which is not what we want, I prefer to have all the options (flags, envs).
* It does not add the ability to have the `AWS_*` env variables which are the ones supported by TF and AWS-SDK, which is what we want.

At least this is what I saw on the link you provided :smile:

**Comment by kevit** [comment]
it is not so easy as I tought anyway,  reader needs to be rewritten as well like here
https://github.com/hashicorp/terraform/blob/master/vendor/github.com/aws/aws-sdk-go/aws/credentials/shared_credentials_provider.go

**Comment by xescugc** [comment]
> it is not so easy as I tought anyway

Yep, it's not hehe

> reader needs to be rewritten as well like here

Yeh I did not comment on that as I would not have worked for sure that change.

The idea would be not to make that part of the code read env, but receive params to initialize, like it's doing now.

**Comment by xescugc** [comment]
With https://github.com/cycloidio/terracognita/pull/142 we included the hability to read from the credentials as documented on https://github.com/cycloidio/terracognita/issues/48#issuecomment-524394788.

We've also changed the flags to be more AWS/TF friendly, which basically means having the same names that they use.

**Comment by xescugc** [comment]
For me works perfectly

```
~/tc-test $> terracognita aws --aws-profile cycloid -i aws_instance --hcl out.hcl --aws-default-region eu-west-1
Starting Terracognita with version v0.7.4
Importing with filters: 
	Tags:    [],
	Include: [aws_instance],
	Exclude: [],
	Targets: [],
Importing aws_instance [26/26] Done!
Writing HCL Done!
```

And the profiles are on:
```
~ $> cat .aws/credentials 
[cycloid]
aws_access_key_id={the-cool-access-key}
aws_secret_access_key={the-cool-secret-key}
```

**Comment by csutera** [comment]
I am experiencing an error with this cmd
```
terracognita aws --aws-profile $AWS_PROFILE s3 --aws-default-region us-east-1 --module terra -v
```

results in 
```
could not initialize 'reader' because: ExpiredToken: The security token included in the request is expired
	status code: 403, request id:
```

despite 
```
 aws s3 ls --profile $AWS_PROFILE
```
successfully listing buckets

**Comment by xescugc** [comment]
Ok so the first thing I can see it's the `--aws-profile $AWS_PROFILE s3` the `s3` can be dropped as it's ignored an would do nothing :), if you want to filter specific resources you have to use `--include`.

Also if you have it already as an ENV variable you can avoid setting it as a flag as it reads it from envs too.

All this said, I cannot tell you why AWS in terracognita case returns `ExpiredToken: The security token included in the request is expired` and for the AWS CLI works fine.

We have tested locally the same command you did and works fine for us.

```
~/tc-test $> terracognita aws --aws-profile $AWS_PROFILE s3 --aws-default-region eu-west-1 --module terra
We are about to remove all content from "terra", are you sure? Yes/No (Y/N):
y
Starting Terracognita with version v0.7.4
Importing with filters: 
	Tags:    [],
	Include: [],
	Exclude: [],
	Targets: [],
Importing aws_instance [1/28]^C
```
---

Looking around I've found https://aws.amazon.com/premiumsupport/knowledge-center/ec2-expired-token/ which may help you solve the issue potentially. I don't know if you  ran them on the same CMD or not but

> Another reason for expiration is using the incorrect time. A consistent and accurate time reference is crucial for many server tasks and processes. If your instance's date and time aren't set correctly, the AWS credentials are rejected.

looks like a good place to start hehe.

If this  does not help  you solve the issue i'll open an specific issue to tackle your case and investigate.
